import * as fs from 'fs';
import * as path from 'path';
import { Memory, MemoryType } from '../../shared/types';
import { getMemoriesForInjection } from '../repositories/memories';

const MEMORY_FILENAME = '.claudelander-memory.md';
const MAX_FILE_SIZE = 8 * 1024; // 8KB limit

/**
 * Format memories into markdown sections by type.
 */
function formatMemories(memories: Memory[]): string {
  const sections: Record<MemoryType, Memory[]> = {
    decision: [],
    error_fix: [],
    pattern: [],
    context: [],
    note: [],
  };

  // Group memories by type
  for (const memory of memories) {
    sections[memory.type].push(memory);
  }

  const lines: string[] = [
    '# Session Memory',
    '*Auto-generated by ClaudeLander - Do not edit manually*',
    '',
  ];

  // Add pinned memories first
  const pinnedMemories = memories.filter(m => m.pinned);
  if (pinnedMemories.length > 0) {
    lines.push('## Pinned');
    for (const memory of pinnedMemories) {
      const date = memory.createdAt instanceof Date
        ? memory.createdAt.toISOString().split('T')[0]
        : new Date(memory.createdAt).toISOString().split('T')[0];
      lines.push(`- [${date}] ${memory.content}`);
    }
    lines.push('');
  }

  // Add each type section
  const sectionTitles: Record<MemoryType, string> = {
    decision: 'Decisions',
    error_fix: 'Error Fixes',
    pattern: 'Patterns',
    context: 'Context',
    note: 'Notes',
  };

  for (const [type, title] of Object.entries(sectionTitles)) {
    const typeMemories = sections[type as MemoryType].filter(m => !m.pinned);
    if (typeMemories.length > 0) {
      lines.push(`## ${title}`);
      for (const memory of typeMemories) {
        const date = memory.createdAt instanceof Date
          ? memory.createdAt.toISOString().split('T')[0]
          : new Date(memory.createdAt).toISOString().split('T')[0];
        lines.push(`- [${date}] ${memory.content}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Write the memory file to the session's working directory.
 * Creates or updates the .claudelander-memory.md file.
 */
export function writeMemoryFile(
  sessionId: string,
  groupId: string,
  workingDir: string
): void {
  try {
    // Get memories for this session
    const memories = getMemoriesForInjection(sessionId, groupId);

    if (memories.length === 0) {
      // Remove file if it exists and there are no memories
      const filePath = path.join(workingDir, MEMORY_FILENAME);
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
        console.log(`[Memory] Removed empty memory file: ${filePath}`);
      }
      return;
    }

    // Format memories to markdown
    const content = formatMemories(memories);

    // Check size limit
    if (content.length > MAX_FILE_SIZE) {
      console.warn(`[Memory] Memory file exceeds ${MAX_FILE_SIZE} bytes, truncating`);
    }

    // Write file
    const filePath = path.join(workingDir, MEMORY_FILENAME);
    fs.writeFileSync(filePath, content.slice(0, MAX_FILE_SIZE), 'utf-8');
    console.log(`[Memory] Wrote memory file: ${filePath} (${content.length} bytes, ${memories.length} memories)`);
  } catch (err) {
    console.error('[Memory] Failed to write memory file:', err);
  }
}

/**
 * Remove the memory file from a working directory.
 * Call this when a session ends if cleanup is desired.
 */
export function removeMemoryFile(workingDir: string): void {
  try {
    const filePath = path.join(workingDir, MEMORY_FILENAME);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      console.log(`[Memory] Removed memory file: ${filePath}`);
    }
  } catch (err) {
    console.error('[Memory] Failed to remove memory file:', err);
  }
}

/**
 * Check if a memory file exists in the working directory.
 */
export function hasMemoryFile(workingDir: string): boolean {
  const filePath = path.join(workingDir, MEMORY_FILENAME);
  return fs.existsSync(filePath);
}
