import * as fs from 'fs';
import * as path from 'path';
import { Memory, MemoryType, GLOBAL_CONTEXT_GROUP_ID } from '../../shared/types';
import { getMemoriesForInjection } from '../repositories/memories';

const MEMORY_FILENAME = '.bodhilander-memory.md';
const MAX_FILE_SIZE = 8 * 1024; // 8KB limit

/**
 * Format memories into markdown sections by type.
 */
function formatMemories(memories: Memory[]): string {
  const sections: Record<MemoryType, Memory[]> = {
    decision: [],
    error_fix: [],
    pattern: [],
    context: [],
    note: [],
  };

  // Group memories by type
  for (const memory of memories) {
    sections[memory.type].push(memory);
  }

  const lines: string[] = [
    '# Session Memory',
    '*Auto-generated by Bodhilander - Do not edit manually*',
    '',
  ];

  // Add pinned memories first
  const pinnedMemories = memories.filter(m => m.pinned);
  if (pinnedMemories.length > 0) {
    lines.push('## Pinned');
    for (const memory of pinnedMemories) {
      const date = memory.createdAt instanceof Date
        ? memory.createdAt.toISOString().split('T')[0]
        : new Date(memory.createdAt).toISOString().split('T')[0];
      lines.push(`- [${date}] ${memory.content}`);
    }
    lines.push('');
  }

  // Add each type section
  const sectionTitles: Record<MemoryType, string> = {
    decision: 'Decisions',
    error_fix: 'Error Fixes',
    pattern: 'Patterns',
    context: 'Context',
    note: 'Notes',
  };

  for (const [type, title] of Object.entries(sectionTitles)) {
    const typeMemories = sections[type as MemoryType].filter(m => !m.pinned);
    if (typeMemories.length > 0) {
      lines.push(`## ${title}`);
      for (const memory of typeMemories) {
        const date = memory.createdAt instanceof Date
          ? memory.createdAt.toISOString().split('T')[0]
          : new Date(memory.createdAt).toISOString().split('T')[0];
        lines.push(`- [${date}] ${memory.content}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Write the memory file to the session's working directory.
 * Creates or updates the .bodhilander-memory.md file.
 */
export function writeMemoryFile(
  sessionId: string,
  groupId: string,
  workingDir: string
): void {
  try {
    // Get memories for this session
    const memories = getMemoriesForInjection(sessionId, groupId);

    if (memories.length === 0) {
      // Remove file if it exists and there are no memories
      const filePath = path.join(workingDir, MEMORY_FILENAME);
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
        console.log(`[Memory] Removed empty memory file: ${filePath}`);
      }
      return;
    }

    // Format memories to markdown
    const content = formatMemories(memories);

    // Check size limit
    if (content.length > MAX_FILE_SIZE) {
      console.warn(`[Memory] Memory file exceeds ${MAX_FILE_SIZE} bytes, truncating`);
    }

    // Write file
    const filePath = path.join(workingDir, MEMORY_FILENAME);
    fs.writeFileSync(filePath, content.slice(0, MAX_FILE_SIZE), 'utf-8');
    console.log(`[Memory] Wrote memory file: ${filePath} (${content.length} bytes, ${memories.length} memories)`);
  } catch (err) {
    console.error('[Memory] Failed to write memory file:', err);
  }
}

/**
 * Remove the memory file from a working directory.
 * Call this when a session ends if cleanup is desired.
 */
export function removeMemoryFile(workingDir: string): void {
  try {
    const filePath = path.join(workingDir, MEMORY_FILENAME);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      console.log(`[Memory] Removed memory file: ${filePath}`);
    }
  } catch (err) {
    console.error('[Memory] Failed to remove memory file:', err);
  }
}

/**
 * Check if a memory file exists in the working directory.
 */
export function hasMemoryFile(workingDir: string): boolean {
  const filePath = path.join(workingDir, MEMORY_FILENAME);
  return fs.existsSync(filePath);
}

/**
 * Get formatted memory content for system prompt injection.
 * Returns content suitable for --append-system-prompt CLI flag.
 * Returns null if no groupId provided, otherwise returns XML-wrapped content
 * with either existing memories or a placeholder for saving new ones.
 */
export function getMemoryInjectionContent(
  sessionId: string,
  groupId: string,
  workingDir?: string
): string | null {
  if (!groupId) {
    return null;
  }

  const memories = getMemoriesForInjection(sessionId, groupId);

  // Separate global context from project context
  const globalMemories = memories.filter(m => m.groupId === GLOBAL_CONTEXT_GROUP_ID);
  const projectMemories = memories.filter(m => m.groupId !== GLOBAL_CONTEXT_GROUP_ID);

  // Build global context items
  const globalItems: string[] = [];
  for (const memory of globalMemories) {
    const prefix = memory.pinned ? '[PINNED] ' : '';
    globalItems.push(`- ${prefix}${memory.content}`);
  }

  // Build project context items
  const projectItems: string[] = [];
  const pinnedProject = projectMemories.filter(m => m.pinned);
  const otherProject = projectMemories.filter(m => !m.pinned);

  for (const memory of pinnedProject) {
    projectItems.push(`- ${memory.content} [PINNED]`);
  }
  for (const memory of otherProject) {
    projectItems.push(`- ${memory.content}`);
  }

  const sections: string[] = [];

  // Add global context section if present
  if (globalItems.length > 0) {
    sections.push(`Global context (applies to all projects):
${globalItems.join('\n')}`);
  }

  // Add project context section if present
  if (projectItems.length > 0) {
    sections.push(`Project context:
${projectItems.join('\n')}`);
  }

  if (sections.length === 0) {
    // No memories yet, just provide group_id for saving new ones
    return `<session-memories>
No saved context for this session yet.
To save new context, use the MCP tool with group_id: ${groupId}
For global context (all projects), use group_id: ${GLOBAL_CONTEXT_GROUP_ID}
</session-memories>`;
  }

  // Format as multi-line system prompt content
  return `<session-memories>
You have saved context from previous sessions:

${sections.join('\n\n')}

To save new context, use the MCP tool with group_id: ${groupId}
For global context (all projects), use group_id: ${GLOBAL_CONTEXT_GROUP_ID}
</session-memories>`;
}
