-- 002_sharing.sql — session sharing (Milestone 5.1).
--
-- The relay stores routing and an opaque blob. It is a COARSE GATE, not the
-- authority: `machine_grants.certificate` is signed by the desktop and is
-- meaningless here, and no session id ever reaches this database. The session
-- list that a grant actually covers lives only in the owner's desktop tables,
-- which is what makes guests structurally invisible to the relay.
--
-- Timestamps are INTEGER unix milliseconds, matching 001.
--
-- NOTE: the `link_codes.user_id` FK repair is deliberately NOT bundled here.
-- runMigrations wraps each file in a transaction and SQLite makes
-- `PRAGMA foreign_keys` a no-op inside one, so the standard 12-step table
-- rebuild does not apply cleanly. It is an unrelated pre-existing defect and
-- wants its own migration plus a volume snapshot in the runbook.

CREATE TABLE IF NOT EXISTS share_invites (
  id TEXT PRIMARY KEY,
  machine_id TEXT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL UNIQUE,
  -- Addressed invites: only this GitHub login may redeem. NULL is an open link.
  expected_github_login TEXT,
  role TEXT NOT NULL CHECK(role IN ('viewer','operator')),
  label TEXT,
  grant_ttl_seconds INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','redeemed','revoked')),
  redeemed_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  redeemed_at INTEGER,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL
);

-- Deliberately NO UNIQUE(machine_id, grantee_user_id). Sharing a second
-- session with the same colleague is the first thing anyone will do, and it
-- must be a second grant rather than an in-place widening of the first. The
-- effective scope of a client is the union of the certificates it presents,
-- resolved by the agent. The id is generated by the DESKTOP, and the agent
-- refuses any certificate whose grantId is not in its own table — so a reused
-- id cannot silently hand one grant's holder another grant's sessions.
CREATE TABLE IF NOT EXISTS machine_grants (
  id TEXT PRIMARY KEY,
  machine_id TEXT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  grantee_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invite_id TEXT REFERENCES share_invites(id) ON DELETE SET NULL,
  -- Opaque to the relay; NULL until the agent countersigns.
  certificate TEXT,
  role TEXT NOT NULL CHECK(role IN ('viewer','operator')),
  -- Display hint only. NEVER authorization.
  label TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','revoked')),
  created_at INTEGER NOT NULL,
  bound_at INTEGER,
  expires_at INTEGER,
  revoked_at INTEGER,
  last_used_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_machine_grants_grantee ON machine_grants(grantee_user_id, status);
CREATE INDEX IF NOT EXISTS idx_machine_grants_machine ON machine_grants(machine_id, status);
CREATE INDEX IF NOT EXISTS idx_machine_grants_expires_at ON machine_grants(expires_at);
CREATE INDEX IF NOT EXISTS idx_share_invites_machine ON share_invites(machine_id, status);
CREATE INDEX IF NOT EXISTS idx_share_invites_expires_at ON share_invites(expires_at);
