/**
 * Full-screen QR-code scanner overlay used by the /pair flow (BDHLNDR-14).
 *
 * Wraps the `qr-scanner` library so the page only has to mount this
 * component when the user taps "Scan QR" — that satisfies the iOS Safari
 * rule that `getUserMedia` must be invoked from a user gesture.
 *
 * Contract with the desktop QR payload (generated by
 * src/main/api/routes/pairing.ts:42-56):
 *
 *   { type: 'bodhilander-pair', host: string, port: number,
 *     code: string, hostname: string, expiresAt: number }
 *
 * Only `type`, `code`, and `expiresAt` are required for the confirm POST;
 * the rest are forwarded to the consumer in case future flows need them.
 */
import { useEffect, useRef, useState } from 'react';
import QrScanner from 'qr-scanner';

export interface PairPayload {
  type: 'bodhilander-pair';
  host: string;
  port: number;
  code: string;
  hostname: string;
  expiresAt: number;
}

export interface QrScannerProps {
  onScan: (payload: PairPayload) => void;
  onError: (err: Error) => void;
  onCancel: () => void;
}

/**
 * Time, in ms, the user has to land a valid scan before we give up and
 * call `onError`. 30s matches the desktop's pairing-code TTL and is long
 * enough that the user can fumble with focus / lighting without timing
 * out mid-attempt.
 */
const SCAN_TIMEOUT_MS = 30_000;

/**
 * How long a transient "Not a Bodhilander code" hint stays on screen
 * after an invalid (but well-formed) QR scan. Long enough to read,
 * short enough not to feel sticky.
 */
const INVALID_HINT_MS = 1_500;

/**
 * Parse + validate a raw QR string. Returns the payload on success or
 * null if anything is off (parse error, wrong type, expired, wrong
 * shape). Caller treats null as "ignore this scan and keep scanning".
 */
export function parsePairPayload(raw: string): PairPayload | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (parsed === null || typeof parsed !== 'object') return null;
  const obj = parsed as Record<string, unknown>;
  if (obj.type !== 'bodhilander-pair') return null;
  if (typeof obj.code !== 'string' || obj.code.length === 0) return null;
  if (typeof obj.host !== 'string') return null;
  if (typeof obj.port !== 'number') return null;
  if (typeof obj.hostname !== 'string') return null;
  if (typeof obj.expiresAt !== 'number') return null;
  // Reject expired codes outright — the desktop would reject them anyway,
  // but a clean client-side check means we don't ship a stale code to the
  // server and produces a clearer "expired" UX downstream.
  if (obj.expiresAt <= Date.now()) return null;
  return {
    type: 'bodhilander-pair',
    host: obj.host,
    port: obj.port,
    code: obj.code,
    hostname: obj.hostname,
    expiresAt: obj.expiresAt,
  };
}

export function QrScannerOverlay({ onScan, onError, onCancel }: QrScannerProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const scannerRef = useRef<QrScanner | null>(null);
  // Guards against firing onScan / onError twice for the same mount —
  // the qr-scanner can yield multiple decodes between the moment we
  // decide to stop and the moment the stream actually stops.
  const settledRef = useRef(false);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const invalidHintTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [invalidHintVisible, setInvalidHintVisible] = useState(false);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    // Safety net: if the browser somehow exposes a navigator but no
    // mediaDevices (very old Safari), bail before instantiating the
    // scanner — the parent component should already have hidden the
    // button, but defense in depth.
    if (
      typeof navigator === 'undefined' ||
      !navigator.mediaDevices ||
      typeof navigator.mediaDevices.getUserMedia !== 'function'
    ) {
      settledRef.current = true;
      onError(new Error('Camera not supported on this device'));
      return;
    }

    const scanner = new QrScanner(
      video,
      (result) => {
        if (settledRef.current) return;
        const payload = parsePairPayload(result.data);
        if (!payload) {
          // Not our QR — show a transient hint and keep scanning.
          setInvalidHintVisible(true);
          if (invalidHintTimeoutRef.current) {
            clearTimeout(invalidHintTimeoutRef.current);
          }
          invalidHintTimeoutRef.current = setTimeout(() => {
            setInvalidHintVisible(false);
          }, INVALID_HINT_MS);
          return;
        }
        settledRef.current = true;
        // Stop the camera before handing control back to the caller so
        // we don't keep the light on while the network request runs.
        scanner.stop();
        if (timeoutRef.current) clearTimeout(timeoutRef.current);
        onScan(payload);
      },
      {
        // Prefer the back camera on phones — front camera (`user`) is
        // basically useless for scanning a screen you're holding the
        // phone up to.
        preferredCamera: 'environment',
        // qr-scanner ships an `onDecodeError` for every frame that
        // failed to decode; firing that into our caller would spam.
        // We deliberately no-op it and rely on the timeout instead.
        onDecodeError: () => {
          /* noop — too noisy to surface */
        },
        highlightScanRegion: true,
        highlightCodeOutline: true,
        // Required by the new qr-scanner API to opt into the
        // ScanResult-with-cornerPoints shape we typed against.
        returnDetailedScanResult: true,
      },
    );
    scannerRef.current = scanner;

    scanner
      .start()
      .then(() => {
        // Only arm the timeout after the camera actually started — if
        // start() rejected (e.g. permission denied) we surface that
        // immediately via the catch below and don't want a phantom
        // "Scan timed out" 30s later.
        if (settledRef.current) return;
        timeoutRef.current = setTimeout(() => {
          if (settledRef.current) return;
          settledRef.current = true;
          scanner.stop();
          onError(new Error('Scan timed out'));
        }, SCAN_TIMEOUT_MS);
      })
      .catch((err: unknown) => {
        if (settledRef.current) return;
        settledRef.current = true;
        // Distinguish denial from "no camera at all" so the parent
        // pair page can render the right inline hint.
        const message =
          err instanceof Error && /denied|permission|NotAllowed/i.test(err.message)
            ? 'Camera access denied'
            : 'Could not start camera';
        onError(new Error(message));
      });

    return () => {
      // Mark settled first so any in-flight decode callbacks short-circuit.
      settledRef.current = true;
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
        timeoutRef.current = null;
      }
      if (invalidHintTimeoutRef.current) {
        clearTimeout(invalidHintTimeoutRef.current);
        invalidHintTimeoutRef.current = null;
      }
      // destroy() stops the stream, releases the camera, and tears down
      // the worker. Belt-and-suspenders: also walk the video's srcObject
      // tracks in case qr-scanner ever leaves one dangling on an early
      // teardown (start() rejecting before its own cleanup runs).
      scannerRef.current?.destroy();
      scannerRef.current = null;
      const stream = video.srcObject;
      if (stream && stream instanceof MediaStream) {
        for (const track of stream.getTracks()) {
          track.stop();
        }
        video.srcObject = null;
      }
    };
    // We intentionally only set up the scanner once per mount — re-running
    // on every callback identity change would re-request the camera.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleCancel() {
    if (settledRef.current) return;
    settledRef.current = true;
    scannerRef.current?.stop();
    onCancel();
  }

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Scan pairing QR code"
      className="fixed inset-0 z-50 flex flex-col bg-black"
    >
      <video
        ref={videoRef}
        // qr-scanner manages playsInline / muted internally, but
        // declaring them defensively avoids iOS auto-fullscreening
        // the video element.
        playsInline
        muted
        className="h-full w-full object-cover"
      />
      <div className="pointer-events-none absolute inset-x-0 top-0 p-4 text-center text-sm text-white drop-shadow-lg">
        Point the camera at the QR code on your desktop.
      </div>
      {invalidHintVisible && (
        <div
          role="status"
          aria-live="polite"
          className="pointer-events-none absolute inset-x-0 top-16 mx-auto w-fit rounded-md bg-black/70 px-3 py-1.5 text-sm text-white"
        >
          Not a Bodhilander code
        </div>
      )}
      <button
        type="button"
        onClick={handleCancel}
        className="absolute inset-x-0 bottom-6 mx-auto block w-fit rounded-full bg-white/15 px-6 py-3 text-base font-medium text-white backdrop-blur transition-colors hover:bg-white/25"
      >
        Cancel
      </button>
    </div>
  );
}

/**
 * Whether `getUserMedia` is available in the current browser. The Pair
 * page calls this to decide whether to render the "Scan QR" button at
 * all — there's no point offering scan-mode to someone whose browser
 * can't access the camera.
 */
export function isCameraSupported(): boolean {
  if (typeof navigator === 'undefined') return false;
  return Boolean(navigator.mediaDevices?.getUserMedia);
}
